from .base_learner import DenverLearner
from .flair_sequence_tagger_leaner import FlairSequenceTaggerLearner
from .ulmfit_cls_learner import ULMFITClassificationLearner
from .onenet_learner import OnenetLearner